name: release sample

on:
  push:
    tags:
      - 'test-release-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}

jobs:
  prepare-build:
    name: Prepare Build
    outputs:
      targets: ${{ steps.all-targets.outputs.targets }}
      image-tag: ${{ steps.resolve.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python: false
          go: false

      - name: Container image
        id: resolve
        run: |
          _target=${GITHUB_REF_NAME#test-release-}

          # get version only
          version=${_target##*-v}
          echo version=${version} >> ${GITHUB_OUTPUT}

          echo "Version: $version"

  release:
    name: Build docker image - ${{ matrix.target }}
    needs: [prepare-build]
    runs-on: ubuntu-latest
    steps:
      - name: run test release
        id: release
        env:
          IMAGE_TAG: ${{ needs.prepare-build.outputs.image-tag }}
        run: |
          echo $IMAGE_TAG
